#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
environment=${ENVIRONMENT:-development}
aws_profile=${AWS_PROFILE:-admin}
aws_region=${AWS_REGION:-us-east-2}
state_bucket=template-monorepo-terraform-state
app_workspace=workspace/personal/template-monorepo
state_workspace=workspace/personal/config-state
app_dir="$repo_root/$app_workspace/app"
image_tfvars="$repo_root/$app_workspace/environments/$environment/image.tfvars"
repository_name="template-monorepo-$environment/api"

case "$environment" in
  development|staging|production) ;;
  *) printf 'Unsupported environment: %s\n' "$environment" >&2; exit 2 ;;
esac

cd "$repo_root"

for command_name in aws bun cut docker git jq make sha256sum sort terraform xargs; do
  command -v "$command_name" >/dev/null 2>&1 || {
    printf 'Required command is not installed: %s\n' "$command_name" >&2
    exit 1
  }
done

docker info >/dev/null 2>&1 || {
  printf 'Docker is installed, but its daemon is unavailable.\n' >&2
  exit 1
}

test -d "$app_dir/.git" || {
  printf 'Application checkout is missing: %s\n' "$app_dir" >&2
  exit 1
}

printf 'Checking Terraform state foundation...\n'
make discover >/dev/null
if ! jq -e --arg bucket "$state_bucket" '.Buckets[]? | select(.Name == $bucket)' .aws-discovery/s3-buckets.json >/dev/null; then
  printf 'Creating Terraform state bucket %s...\n' "$state_bucket"
  make plan WORKSPACE="$state_workspace" ENVIRONMENT=production LOCAL_BACKEND=true
  make apply WORKSPACE="$state_workspace" ENVIRONMENT=production LOCAL_BACKEND=true
  make discover >/dev/null
  jq -e --arg bucket "$state_bucket" '.Buckets[]? | select(.Name == $bucket)' .aws-discovery/s3-buckets.json >/dev/null \
    || { printf 'State bucket verification failed: %s\n' "$state_bucket" >&2; exit 1; }
fi

printf 'Bootstrapping the %s container registry...\n' "$environment"
make bootstrap-registry \
  WORKSPACE="$app_workspace" \
  ENVIRONMENT="$environment" \
  AWS_PROFILE="$aws_profile" \
  AWS_REGION="$aws_region"

repository_url=$(aws ecr describe-repositories \
  --repository-names "$repository_name" \
  --profile "$aws_profile" \
  --region "$aws_region" \
  --query 'repositories[0].repositoryUri' \
  --output text)
registry=${repository_url%/*}
git_revision=$(git -C "$app_dir" rev-parse --short=12 HEAD)
source_digest=$(
  cd "$app_dir"
  git ls-files --cached --others --exclude-standard -z \
    | sort -z \
    | xargs -0 sha256sum \
    | sha256sum \
    | cut -c1-12
)
image_tag="$git_revision-$source_digest"

printf 'Building application image %s:%s...\n' "$repository_url" "$image_tag"
docker build --pull --tag "$repository_url:$image_tag" "$app_dir"

printf 'Authenticating Docker to ECR...\n'
aws ecr get-login-password --profile "$aws_profile" --region "$aws_region" \
  | docker login --username AWS --password-stdin "$registry" >/dev/null

image_digest=$(aws ecr describe-images \
  --repository-name "$repository_name" \
  --image-ids "imageTag=$image_tag" \
  --profile "$aws_profile" \
  --region "$aws_region" \
  --query 'imageDetails[0].imageDigest' \
  --output text 2>/dev/null || true)

if [ -z "$image_digest" ] || [ "$image_digest" = None ]; then
  printf 'Pushing application image...\n'
  docker push "$repository_url:$image_tag"
  image_digest=$(aws ecr describe-images \
    --repository-name "$repository_name" \
    --image-ids "imageTag=$image_tag" \
    --profile "$aws_profile" \
    --region "$aws_region" \
    --query 'imageDetails[0].imageDigest' \
    --output text)
else
  printf 'ECR already contains this immutable commit image; reusing it.\n'
fi

case "$image_digest" in
  sha256:????????????????????????????????????????????????????????????????) ;;
  *) printf 'ECR returned an invalid image digest.\n' >&2; exit 1 ;;
esac

umask 077
{
  printf '# Generated by apply.sh; do not edit.\n'
  printf 'container_image      = "%s@%s"\n' "$repository_url" "$image_digest"
  printf 'container_port       = 3000\n'
  printf 'health_check_path    = "/api/health"\n'
  printf 'health_check_command = ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/health || exit 1"]\n'
} >"$image_tfvars"

printf 'Planning %s environment...\n' "$environment"
make plan \
  WORKSPACE="$app_workspace" \
  ENVIRONMENT="$environment" \
  AWS_PROFILE="$aws_profile" \
  AWS_REGION="$aws_region" \
  EXTRA_TFVARS="$image_tfvars"

printf 'Applying %s environment...\n' "$environment"
make apply \
  WORKSPACE="$app_workspace" \
  ENVIRONMENT="$environment" \
  AWS_PROFILE="$aws_profile" \
  AWS_REGION="$aws_region"

terraform_dir="$repo_root/dist/personal/template-monorepo/infra"
api_url=$(terraform -chdir="$terraform_dir" output -raw api_url)
frontend_url=$(terraform -chdir="$terraform_dir" output -raw frontend_url)
frontend_bucket=$(terraform -chdir="$terraform_dir" output -raw frontend_bucket_name)
frontend_distribution=$(terraform -chdir="$terraform_dir" output -raw frontend_distribution_id)

printf 'Building Vite frontend for %s...\n' "$api_url"
(
  cd "$app_dir"
  bun install --frozen-lockfile
  VITE_API_URL="$api_url" bun run build:vite
)

printf 'Publishing frontend to %s...\n' "$frontend_url"
aws s3 sync "$app_dir/apps/vite/dist" "s3://$frontend_bucket" \
  --delete \
  --exclude 'assets/*' \
  --exclude index.html \
  --cache-control 'no-cache' \
  --profile "$aws_profile" \
  --region "$aws_region"
aws s3 sync "$app_dir/apps/vite/dist/assets" "s3://$frontend_bucket/assets" \
  --delete \
  --cache-control 'public,max-age=31536000,immutable' \
  --profile "$aws_profile" \
  --region "$aws_region"
aws s3 cp "$app_dir/apps/vite/dist/index.html" "s3://$frontend_bucket/index.html" \
  --cache-control 'no-cache' \
  --content-type 'text/html; charset=utf-8' \
  --profile "$aws_profile" \
  --region "$aws_region"
aws cloudfront create-invalidation \
  --distribution-id "$frontend_distribution" \
  --paths '/*' \
  --profile "$aws_profile" \
  --region us-east-1 \
  --output text \
  --query 'Invalidation.Id'

printf 'Deployment complete. Terraform outputs:\n'
terraform -chdir="$terraform_dir" output
